### ISSUE TITLE
False image path cousing images showen randomly mixed on FritzFon

### ISSUE THREAD

**Issue by holzhannes** [jens-maus/carddav2fb#13]
My FritzFon MT-F Firmware 01.03.67 in connection with FritzBox 7490 (UI) Firmware 06.50 seems to need file:///var/InternerSpeicher/FRITZ/fonpix/ prefix in the .xml document instead of file:///var/media/ftp/FRITZ/fonpix/ to show the images correctly.

Please note: If you look in the FritzBox the images will be shown correctly but on the phone the contacts have false images.

**Comment by jens-maus** [comment]
I hope this is also solved by your own changes now. If not please reopen.
