### ISSUE TITLE
improvement: convenient image upload – imagenumber instead of imagename

### ISSUE THREAD

**Issue by holzhannes** [jens-maus/carddav2fb#14]
I did some minor changes, in the carddav2fb.php. This makes it easier to add a lot of images.
First create many files with a dimension of only 1x1 pixel with sequential numbers from 1.jpg to let say 1000.jpg and compress these Images. Therefore they are very small and you just upload them to your FritzBox /FRITZ/fonpix folder in some seconds.

After that just change the the following lines in carddav2fb.php.

in line 149 I added: ```$imgseqfname = 1;```
comment the lines 200 and 201 with ```// ``` infront and add these two lines after line 201: 
```$photo = $imgseqfname; 
$imgseqfname++;```

That's all now you don't have to upload images manual again. The 1x1 pixel images will just be replaced by your real contact images.

**Comment by jens-maus** [comment]
Now that your changes have been merged, I think we can close that one here.
