### ISSUE TITLE
Not Working under Windows / curl-error

### ISSUE THREAD

**Issue by ArnaudFeld** [jens-maus/carddav2fb#23]
Hi Guys,

when i try to use the Script under Windows i get following error.

Script is the Last commit.
I try different Version of PHP. From 5.4 up to 7.

Any Suggestion what i can make to fix?

![bildschirmfoto 2016-04-07 um 14 43 51](https://cloud.githubusercontent.com/assets/1561416/14351387/3e35b3ca-fccf-11e5-8c3b-a09874374578.jpg)

**Comment by jens-maus** [comment]
No idea. Real nerds like me use Unix/Linux only ;)

**Comment by ArnaudFeld** [comment]
I also with OS X ;-)
It's a PC of a Friend

**Comment by jens-maus** [comment]
OSX is more or less Unix. So tell your friend so switch. ;) But to be serious: I am sorry but I can't help here. Looks like some PHP modules are missing.

**Comment by ArnaudFeld** [comment]
UNIX is the mother of all ;)

Thanks

He can't switch (long story).

Then he must wait until his rPi is online!
Or I connected via VPN from my rPi to his Box and use the script so.

I will try ;)

Von meinem iPhone gesendet

**Comment by jens-maus** [comment]
I had the same problem now recently. The reason for this error message is that the "php-curl" extension is missing and required for carddav2fb to work properly. On Ubuntu one would install this extension via the following command:

`sudo apt-get install php-curl`

How this is done on Windows, I can't tell – but he might be able to look it up.
