### ISSUE TITLE
photos referenced by URL are not imported

### ISSUE THREAD

**Issue by Johann-Tree** [jens-maus/carddav2fb#24]
With several contacts I get following error when retrieving the contacts from the server: 
> PHP Warning:  Illegal string offset 'value' carddav2fb.php on line 559

Now I figured out: These are the contacts where the photo on the fritzbox is empty: These contacts have a photo referenced by URL like this:
```
PHOTO:
 http://www.example.org/bilder/image_of_person.jpg
```
Would it be possible to fetch the images from the given URL and import them, too?

**Comment by jens-maus** [comment]
Of course this might be possible. However, first I need to understand two things here:

1. How and where exactly did you put URLs instead of direct photos into the VCard of these persons? Which CardDAV Server do you use?
2. Can you add some debug output at line 559 for outputting what `$entry['photo_data']`contains in these cases? It seems they actually don't have any `['value']` reference?!?

**Comment by Johann-Tree** [comment]
I use Mozilla Thunderbird 38.7.2 for my address book which I store with [SOGo Connector 31.0.2 ](http://sogo.nu/download.html#/frontends) ([Source](https://github.com/inverse-inc/sogo-connector.tb31)) on a Synology NAS (current version DSM 6.0-7321 Update 3 with CardDAVServer 6.0.0-0074). When using the address book of Thunderbird you can either select a photo from your computer or simply provide an URI. (Local images you also find in an vcf-export of the address book, remote images are only referenced by the given URI.)

I added `print_r($entry['photo_data'], $return = null);` at line 559 and got following exemplary output from a contact with a photo referenced by an URI:
> Array
> (
>     [0] =>  http://www.example.org/bilder/image_of_person.jpg
> )

 

Also you are assuming all photos are in JPG format, which is not necessarily true. Luckily you should get the format with `$photo_typ = $entry['photo_data'][0]['type'][0];` .
So we could use that information to create the ending of the file name. (JPGs have "jpeg", PNGs simply "png".)
Shall I create a separate issue for that?

**Comment by jens-maus** [comment]
Well, AFAIK does the FRITZ!Box only accept JPG images to be stored in the telephone books – that's at least what I can see when trying to upload a contact image via the web interface of the FRITZ!Box. So are you sure that PNG files are fine when using them with a FRITZ!fon?

**Comment by Johann-Tree** [comment]
I don't have a FRITZ!fon so can't say anything about that. 
If this is true we would have to convert the image to JPG - not just adding the jpg-suffix.

**Comment by jens-maus** [comment]
I would rather omit non-jpg files completely and not stuff in a complex image conversion routine into carddav2fb now. IMHO it is not the job of carddav2fb to convert these images.

**Comment by Johann-Tree** [comment]
Yeah, your're right.
Ok, than we could just print an according error message.
But maybe we could check if imagemagick is installed and in that case let convert do the job. That would not be much work to code.

**Comment by jens-maus** [comment]
Feel free to submit a pull request! ;)

**Comment by jens-maus** [comment]
Please note my latest update/rework of the photo_data conversion routines. Now I am simply reusing a specified URL in case it is found. And I also also warning if non-jpg photo data was found. Please see if these changes solve your problems.

**Comment by jens-maus** [comment]
I guess that with my latest change this issue is now resolved. Thus, closing this issue.
