### ISSUE TITLE
Blank Character between First- and Lastname possible?

### ISSUE THREAD

**Issue by ArnaudFeld** [jens-maus/carddav2fb#3]
I changed the First- and Lastname in the Script. It works but...

Is there a possibility to make a blank character between First- and Lastname? 
With a comma it works.

At this moment it looks like this: "Firstname, Lastname" but i want like this "Firstname Lastname".

My changed Line 182: 
              $name = $this->_concat($this->_concat($name_arr['firstname'],$name_arr['lastname']),$name_arr['additionalnames']);

**Comment by ArnaudFeld** [comment]
*push*

**Comment by ArnaudFeld** [comment]
Have you a idea @jens-maus ?

**Comment by jens-maus** [comment]
Please test the new ```$config['fullname_format'] = 1;``` config option @holzhannes implemented recently. And if this doesn't work please reopen this ticket.
