### ISSUE TITLE
multiple config files

### ISSUE THREAD

**Issue by mokkin** [jens-maus/carddav2fb#4]
There should be an option to tell the script using a specific config file. So you can use it with different Fritz!Boxes, different users and different addressbooks.

For example:
```
php carddav2fb.php -c config0.php
php carddav2fb.php -c config1.php
php carddav2fb.php -c config2.php
...
```

**Comment by mecks52** [comment]
Seems to be already implemented, the script takes as an argument the name/path of a config file. As default "config.php" is used.
For example:
```
php carddav2fb.php config0.php
php carddav2fb.php config1.php
...
```
See file carddav2fb/carddav2fb.php@dc43cfba96e16ee8b9b7cead7144e5de4c9c8dfa line 30 to 34

**Comment by jens-maus** [comment]
This is indeed correct. So there is no issue here actually, thus I will close that ticket.
